=== saleson/Single/src.resources/single-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.single.com/configuration" xmlns:tns="http://www.single.com/configuration" elementFormDefault="qualified">
	<element name="single-config">
		<complexType>
			<all minOccurs="0">
				<element name="button-mapping" type="tns:button-mapping-type" />
				<element name="style-mapping" type="tns:style-mapping-type" />
				<element name="script-mapping" type="tns:script-mapping-type" />
				<element name="metadata-mapping" type="tns:metadata-mapping-type" />
				<element name="metadata-modify-mapping" type="tns:metadata-modify-mapping-type" />
				<element name="view-mapping" type="tns:view-mapping-type" />
				<element name="view-modify-mapping" />
				<element name="datalayer-mapping" />
				<element name="datalayer-modify-mapping" />
				<element name="sqltable-mapping" />
				<element name="lookup-mapping" />
			</all>
		</complexType>
	</element>
	
	<!-- @button-mapping element 类型 -->
	<complexType name="button-mapping-type">
		<sequence>
			<element name="ImageTextButton" type="tns:ImageTextButton-type" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- @ImageTextButton element 类型 -->
	<complexType name="ImageTextButton-type">
		<attributeGroup ref="tns:base-button-attribute"></attributeGroup>
		<attribute name="imageSrc" type="string"></attribute>
		<attribute name="disableImageSrc" type="string"></attribute>
		<attribute name="group" type="string">
			<annotation>
				<documentation>用于分组合在一起.</documentation>
			</annotation>
		</attribute>
	</complexType>
	
	<!-- @metadata-mapping element 类型 -->
	<complexType name="metadata-mapping-type">
		<sequence>
			<element name="metadata" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<choice maxOccurs="unbounded">
						<element name="field" type="tns:field-type" />
						<element name="edit-field" type="tns:eidt-field-type" />
						<element name="where-field" type="tns:where-field-type" />
					</choice>
					<attribute name="name" type="string"></attribute>
					<attribute name="title" type="string"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
	
	<!-- @metadata-modify-mapping element 类型 -->
	<complexType name="metadata-modify-mapping-type">
		<sequence>
			<element name="metadata-modify" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<choice maxOccurs="unbounded">
						<element name="field" type="tns:field-type" />
						<element name="edit-field" type="tns:eidt-field-type" />
						<element name="where-field" type="tns:where-field-type" />
						<element name="modify-field" type="tns:field-modify-type" />
						<element name="where-modify-field" type="tns:where-field-modify-type" />
					</choice>
					<attribute name="name" type="string"></attribute>
					<attribute name="title" type="string"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
	
	<!-- @view-mapping element 类型 -->
	<complexType name="view-mapping-type">
		<sequence>
			<element name="view" type="tns:view-type" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- @field element 类型 -->
	<complexType name="field-type">
		<attributeGroup ref="tns:base-field-attribute"></attributeGroup>
	</complexType>
	
	
	<!-- @edit-field element 类型 -->
	<complexType name="eidt-field-type">
		<attributeGroup ref="tns:base-edit-field-attribute"></attributeGroup>
	</complexType>
	
	<!-- @edit-field element 类型 -->
 	<complexType name="where-field-type">
		<attributeGroup ref="tns:base-where-field-attribute"></attributeGroup>
	</complexType>
	
	<!-- @field-modify element 类型 -->
 	<complexType name="field-modify-type">
		<attributeGroup ref="tns:base-field-modify-attribute"></attributeGroup>
	</complexType>
	
	<!-- @where-field-modify element 类型 -->
 	<complexType name="where-field-modify-type">
		<attributeGroup ref="tns:base-where-field-modify-attribute"></attributeGroup>
	</complexType>
	
	<!-- @view element 类型 -->
 	<complexType name="view-type">
 		<complexContent>
 			<extension base="tns:base-view-type">
 				<attribute name="pagecode" type="string" use="required"></attribute>
 			</extension>
 		</complexContent>
 	</complexType>
	
	<!-- @view element, view-modify element 等类型的基础 -->
 	<complexType name="base-view-type">
 		<sequence>
 			<!-- 设置页面的属性 -->
 			<element name="set-attribute" type="tns:set-attribute-type" minOccurs="0" maxOccurs="unbounded" />
 			<!-- 设置页面的属性,属性值可以是数组 -->
<!--  			<element name="set-attribute-values" type="tns:set-attribute-values-type" minOccurs="0" maxOccurs="unbounded" /> -->
 			<element name="toolbar" minOccurs="0" maxOccurs="1" type="tns:button-mapping-type" />
 			<element name="header" minOccurs="0" maxOccurs="1" type="tns:pathInclude"></element>
 			<element name="include" minOccurs="0" maxOccurs="unbounded" type="tns:pathInclude"></element>
 			<element name="footer" minOccurs="0" maxOccurs="1" type="tns:pathInclude"></element>
 			<element name="style-include" minOccurs="0" maxOccurs="unbounded" type="tns:style-script-include-type" />
 			<element name="style" minOccurs="0" maxOccurs="unbounded" type="tns:style-type" />
 			<element name="script-include" minOccurs="0" maxOccurs="unbounded" type="tns:style-script-include-type" />
 			<element name="script" minOccurs="0" maxOccurs="unbounded" type="tns:script-type" ></element>
 		</sequence>
		<attribute name="path" type="tns:uri" use="required"></attribute>
		<attribute name="title" type="string" use="optional"></attribute>
 	</complexType>
 	
 	<!-- @view.set-attribute attribute 视图的设置属性的基础属性组 -->
	<complexType name="set-attribute-type">
		<attribute name="key">
 			<simpleType>
				<restriction base="string">
					<enumeration value="list.metadata"></enumeration>
					<enumeration value="master.metadata"></enumeration>
					<enumeration value="slave.metadata"></enumeration>
					<enumeration value="list.location"></enumeration>
					<enumeration value="edit.location"></enumeration>
					<enumeration value="row.onClick"></enumeration>
					<enumeration value="row.onDblClick"></enumeration>
					<enumeration value="page.ismulti"></enumeration><!-- 设置是否有复选框;valu: true , false  -->
					<enumeration value="page.operateType"></enumeration><!-- 页面操作类型:value: showOnly 仅显示, editable 可以编辑  -->
					<enumeration value="page.type"></enumeration><!-- 页面类型. value: viewPage 查看页面, approvalPage 审批页面 -->
					<enumeration value="view.structure"></enumeration><!-- 视图结构. value: List 列表, MasterSlave 主从表 -->
				</restriction>
			</simpleType>
 		</attribute>
 		<attribute name="value" type="string"></attribute>
	</complexType>
 	
 	<!-- @view.set-attribute attribute 视图的设置属性的基础属性组 -->
<!-- 	<complexType name="set-attribute-values-type"> -->
<!-- 		<attribute name="key" type="string"> -->
<!--  			<simpleType> -->
<!-- 				<restriction base="string"> -->
<!-- 					<enumeration value="list.metadata"></enumeration> -->
<!-- 				</restriction> -->
<!-- 			</simpleType> -->
<!--  		</attribute> -->
<!--  		<attribute name="value" type="tns:split"></attribute> -->
<!-- 	</complexType> -->
 	
 	
 	<!-- @style-mapping element 类型 -->
 	<complexType name="style-mapping-type">
 		<sequence>
 			<element name="style" minOccurs="1" maxOccurs="unbounded" type="tns:style-type" />
 		</sequence>
 	</complexType>
 	
 	<!-- @script-mapping element 类型 -->
 	<complexType name="script-mapping-type">
 		<sequence>
 			<element name="script" minOccurs="1" maxOccurs="unbounded" type="tns:script-type" />
 		</sequence>
 	</complexType>
	
	<!-- @style-include, @script-include element 类型 -->
	<complexType name="style-script-include-type">
 		<attribute name="names" type="tns:split"></attribute> 
		<attribute name="method" type="tns:methodADType" default="add"></attribute>
	</complexType>
	
	<!-- @style element 类型 -->
	<complexType name="style-type" mixed="true">
 		<attribute name="name" type="string"></attribute> 
		<attribute name="type" type="string" default="text/css"></attribute>
	</complexType>
	
	<!-- @script element 类型 -->
	<complexType name="script-type" mixed="true">
 		<attribute name="name" type="string"></attribute> 
		<attribute name="type" type="string" default="text/javascript"></attribute>
	</complexType>
	
	<complexType name="pathInclude">
		<attribute name="path" use="required" type="string"></attribute>
		<attribute name="method" type="tns:methodADType" default="add"></attribute>
	</complexType>
	
	
	<!-- 属性:方法 的类型;添加,删除. -->
	<simpleType name="methodADType">
		<restriction base="string">
			<enumeration value="add"></enumeration>
			<enumeration value="delete"></enumeration>
		</restriction>
	</simpleType>
	
	<!-- 属性:方法 的类型;替换,删除. -->
	<simpleType name="methodRDType">
		<restriction base="string">
			<enumeration value="replace"></enumeration>
			<enumeration value="delete"></enumeration>
		</restriction>
	</simpleType>
	
	<!-- 自定义数据类型 -->
	<simpleType name="uri">
		<restriction base="string">
			<pattern value="/{1}[\w/_\-]*(\.[\w]{2,6})(\??\w*=\w*)?(\&amp;?\w*=\w*)?"></pattern>
		</restriction>
	</simpleType>
	
	
	<simpleType name="enDisAbleType">
		<restriction base="string">
			<enumeration value="enabled"></enumeration>
			<enumeration value="disabled"></enumeration>
			<!-- <enumeration value="opened"></enumeration>
			<enumeration value="closed"></enumeration> -->
		</restriction>
	</simpleType>
	
	<simpleType name="inputType">
		<restriction base="string">
			<enumeration value="text"></enumeration>
			<enumeration value="radio"></enumeration>
			<enumeration value="checkbox"></enumeration>
			<enumeration value="hidden"></enumeration>
			<enumeration value="select"></enumeration>
			<enumeration value="multiselect"></enumeration>
			<enumeration value="combox"></enumeration>
			<enumeration value="lookupbox"></enumeration>
			<enumeration value="password"></enumeration>
			<enumeration value="date"></enumeration>
			<enumeration value="time"></enumeration>
			<enumeration value="datetime"></enumeration>
			<enumeration value="image"></enumeration>
			<enumeration value="textarea"></enumeration>
		</restriction>
	</simpleType>
	
	<!-- format格式:0.##最多6个#号,常量QTY_FORMAT等对应的是系统参数-->
	<simpleType name="format">
		<restriction base="string">
			<pattern value="((0)(\.?#){0,6})|yyyy-MM|yyyy-MM-dd|yyyy-MM-dd HH:mm|yyyy-MM-dd HH:mm:ss|\$\{QTY_FORMAT\}"></pattern>
		</restriction>
	</simpleType>
	
	
	<simpleType name="dataType">
		<restriction base="string">
			<enumeration value="varchar"></enumeration>
			<enumeration value="number"></enumeration>
			<enumeration value="date"></enumeration>
			<enumeration value="memo"></enumeration>
			<enumeration value="blob"></enumeration>
			<enumeration value="clob"></enumeration>
		</restriction>
	</simpleType>
	
	<!-- items格式:[{key:'key',name:'name',...},...],必须具备key和name-->
	<simpleType name="items">
		<restriction base="string">
			<!--pattern value="([^,$;]+=[^,$;]+)([,$;][^,$;]+=[^,$;]+){0,}"></pattern-->
			<pattern
				value="\[(\{(key:[\w'()\-]*, name:[\w()'\\$\\.}\\{]*(, (\w*:[\w']*)*)*)\})(,(\{(key:[\w'()\-]*, name:[\w()'\\$\\.}\\{]*(, (\w*:[\w']*)*)*)\}))*\]">
			</pattern>
		</restriction>
	</simpleType>
	
	<!-- split格式:text;text...或text,text...或 text|text...-->
	<simpleType name="split">
		<restriction base="string">
			<pattern value="(.+)([,\|;].+){0,}"></pattern>
		</restriction>
	</simpleType>
	
	<simpleType name="map-string">
		<annotation><documentation><![CDATA[mvel格式的Map<String,String>: ['key1':'value1','key2':'value2',...]]]></documentation></annotation>
		<restriction base="string">
			<!--<pattern value="\[('[\w_/\-\.]*':'[\w_/\-,\.\{\}:]*',)*('[\w_/\-\.]*':'[\w_/\-,\.\{\}:]*')\]"></pattern>-->
			<pattern value="\[('[\w_/\-\.]*':'[\w_/\-,\.\{\}:]*',)*('[\w_/\-\.]*':'.*')\]"></pattern>
		</restriction>
	</simpleType>
	
	<!-- SQL操作符 -->
	<simpleType name="where-opersign">
		<restriction base="string">
			<enumeration value="like"></enumeration>
			<enumeration value="left like"></enumeration>
			<enumeration value="right like"></enumeration>
			<enumeration value="="></enumeration>
			<enumeration value="&gt;"></enumeration>
			<enumeration value="&lt;"></enumeration>
			<enumeration value="&gt;="></enumeration>
			<enumeration value="&lt;="></enumeration>
			<enumeration value="in"></enumeration>
			<enumeration value="not in"></enumeration>
			<enumeration value="between"></enumeration>
		</restriction>
	</simpleType>
	
	<!-- 按钮的基础属性 -->
	<attributeGroup name="base-button-attribute">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="text" type="string"></attribute>
		<attribute name="tooltip" type="string"></attribute>
		<attribute name="onClick" type="string"></attribute>
		<attribute name="index" type="float" default="-1"></attribute>
		<attribute name="initialState" type="tns:enDisAbleType" default="enabled">
			<annotation><documentation>按钮的初始状态,是否可用.</documentation></annotation	>
		</attribute>
		<attribute name="width" type="double"></attribute>
		<attribute name="height" type="double"></attribute>
		<attribute name="enableDetect" type="string"><!-- openedDetect -->
			<annotation>
				<documentation>
					在列表页面中点击新的一行时,判断按钮是否可用的;其内容可以是一个返回boolean类型的函数,也可以是一个判断,反正最终就是要返回一个boolean值.
					并且在js中会将新点击的那一行的值使用with(${rowValueMap}){statement...}封装起来,可能直接写key或字段的名称.
				</documentation>
			</annotation>
		</attribute>
	</attributeGroup>
	
	<!-- 字段的基础属性组 -->
	<attributeGroup name="base-field-attribute">
		<attribute name="name" type="string"></attribute>
		<attribute name="caption" type="string"></attribute>
		<attribute name="primary" type="boolean"></attribute>
		<attribute name="datatype" type="tns:dataType" default="varchar"></attribute>
		<attribute name="format" type="tns:format"></attribute>
		<attribute name="type" type="tns:inputType" default="text"></attribute>
		<attribute name="items" type="tns:items" />
		<attribute name="tip-title" type="string"></attribute>
		<attribute name="display" type="boolean"></attribute>
		<attribute name="index" type="int"></attribute>
	</attributeGroup>
	
	
	<!-- @edit-field attribute 编辑字段的基础属性组 -->
	<attributeGroup name="base-edit-field-attribute">
		<attributeGroup ref="tns:base-field-attribute"></attributeGroup>
		<attribute name="editable" type="boolean" />
		<attribute name="code-rule" type="boolean" />
	</attributeGroup>
	
	<!-- @where-field attribute 编辑字段的基础属性组 -->
	<attributeGroup name="base-where-field-attribute">
		<attributeGroup ref="tns:base-field-attribute"></attributeGroup>
		<attribute name="field" type="string" />
		<attribute name="opersign" type="tns:where-opersign" />
	</attributeGroup>
	
	
	<attributeGroup name="base-field-modify-attribute">
		<attributeGroup ref="tns:base-field-attribute"></attributeGroup>
		<attribute name="editable" type="boolean" />
		<attribute name="method" type="tns:methodRDType" default="replace" />	<!-- add是没用的 -->
	</attributeGroup>
	
	<attributeGroup name="base-where-field-modify-attribute">
		<attributeGroup ref="tns:base-where-field-attribute"></attributeGroup>
		<attribute name="method" type="tns:methodRDType" default="replace" />	<!-- add是没用的 -->
	</attributeGroup>
	
</schema>

=== saleson/Single/WebRoot/WEB-INF/xmlProfiles/public/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<single-config xmlns="http://www.single.com/configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="D:\AppData\git\git\Single\src.resources\single-config.xsd ">
    
    <metadata-mapping>
        <metadata name="md_test_one_list" title="测试页面主表">
            <field name="listTestField0" caption="列表测试字段0" datatype="number" tip-title="列表测试字段0tipTitle" format="0.00"/>
            <field name="listTestField1" caption="列表测试字段1" datatype="number" tip-title="列表测试字段1tipTitle" format="0.00"/>
            <field name="listTestField2" caption="列表测试字段2" datatype="number" tip-title="列表测试字段2tipTitle" format="0.00"/>
            <field name="listTestField3" caption="列表测试字段3" datatype="number" tip-title="列表测试字段3tipTitle" format="0.00"/>
            <field name="listTestField4" caption="列表测试字段4" datatype="number" tip-title="列表测试字段4tipTitle" format="0.00"/>
            <field name="listTestField5" caption="列表测试字段5" datatype="number" tip-title="列表测试字段5tipTitle" format="0.00"/>
            <field name="listTestField6" caption="列表测试字段6" datatype="number" tip-title="列表测试字段6tipTitle" format="0.00"/>
            <field name="listTestField7" caption="列表测试字段7" datatype="number" tip-title="列表测试字段7tipTitle" format="0.00"/>
            <field name="listTestField8" caption="列表测试字段8" datatype="number" tip-title="列表测试字段8tipTitle" format="0.00"/>
            <field name="listTestField9" caption="列表测试字段9" datatype="number" tip-title="列表测试字段9tipTitle" format="0.00"/>
        </metadata>
    </metadata-mapping>
    
    <button-mapping>
        <ImageTextButton name="bn_public_addnew" text="新增" onClick="function addNew()" tooltip="新增单据"/>
    </button-mapping>
    
    <script-mapping>
    	<script name="test1" type="text/javascript">
    		<![CDATA[
    			function addNew(){
    				alert("addNew");
    			}
    		]]>
    	</script>
    </script-mapping>
</single-config>
